### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by LevisAllanon** [PowerShell/PowerShellGallery#157] opened 2021-03-23 02:41 UTC
It seems that the certificate for powershell gallery (https://www.powershellgallery.com/) has expired.
I can't seem to download any modules from the gallery now.

**Comment by Zian** [comment] 2021-03-23 02:45
Same here; IE11 says the certificate was valid to "‎Monday, ‎March ‎22, ‎2021 7:28:06 PM". It's 7:45 PM now in Redmond, Washington.

**Comment by gfree76** [comment] 2021-03-23 03:08
This is a pretty big deal, it's breaking build pipelines that rely on powershell modules

**Comment by alerickson** [comment] 2021-03-23 03:09
Hi all, we're working on this right now.  It looks like the cert got renewed but the thumbprint didn't update.  Currently in the process of making the changes to update to the new thumbprint

**Comment by ganeshnj** [comment] 2021-03-23 03:10
This is very poor experience, it is blocking us (AWS) to release new version of PowerShell Tools.

**Comment by kenwarner** [comment] 2021-03-23 03:16
I am literally trying to install AWS PowerShell tools but can't because of this issue 😂

**Comment by jshield** [comment] 2021-03-23 03:20
@alerickson  did your update thumbprint pipeline depend on powershell gallery?

**Comment by inammathe** [comment] 2021-03-23 03:55
Not a solution but a dodgy workaround...

```
add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
```

**Comment by alerickson** [comment] 2021-03-23 05:04
@jshield fortunately no!  A deployment is underway and this issue should be resolved in half an hour.

**Comment by nexxai** [comment] 2021-03-23 05:17
@alerickson Can you explain how your internal monitors didn't pick up a huge drop in traffic when it expired?

**Comment by kasini3000** [comment] 2021-03-23 05:31
#156

**Comment by theAeon** [comment] 2021-03-23 05:31
> 
> 
> #156

good lord

**Comment by alerickson** [comment] 2021-03-23 05:32
This issue is resolved now.

**Comment by alerickson** [comment] 2021-03-23 05:34
@theAeon @kasini3000 as I mentioned, the cert was renewed but the thumbprint unfortunately didn't updated.

**Comment by theAeon** [comment] 2021-03-23 05:35
> 
> 
> @theAeon @kasini3000 as I mentioned, the cert was renewed but the thumbprint unfortunately didn't updated.

You're fine. Just kinda funny.

Not working on my end just yet.
![image](https://user-images.githubusercontent.com/9099529/112098374-0c157000-8b78-11eb-9543-38221f89dd80.png)

**Comment by inammathe** [comment] 2021-03-23 05:42
Is working now over here in notsosunny Australia Brisbane.

**Comment by theAeon** [comment] 2021-03-23 05:42
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaand its set. Weird.

**Comment by ganeshnj** [comment] 2021-03-23 05:46
Verified, API endpoints are also working. @alerickson thanks for quick turnaround.

**Comment by dev4jaehunkim** [comment] 2021-03-23 05:48
@theAeon I have same issued before. Just close PowerShell terminal and re-open then is working now.
can you re-open terminal?

**Comment by theAeon** [comment] 2021-03-23 05:54
@dev4jaehunkim Its set. Must have been some weird caching stuff going on with the chicago CDN.

**Closed** 2021-03-23 05:57 UTC

**Comment by moria97** [comment] 2021-03-23 06:06
It works. Thanks

**Comment by aapi-rp** [comment] 2021-06-03 04:18
This happened again, its expired right now?  Can this be reopened?

**Comment by pcone** [comment] 2021-06-03 04:24
@aapi-rp There's a new issue here: https://github.com/PowerShell/PowerShellGallery/issues/166

However I agree - this one should just be reopened - manually dealing with whatever issue popped up last time wasn't really a fix, this should be automated (unless it was and this new issue has a different root cause?).

**Comment by Sunitakumari** [comment] 2021-08-18 00:45
We are experiencing same issue again. Powershell galary is not reachable. Can we reopen this issue?
