### ISSUE TITLE
PowerShell Gallery is very slow

### ISSUE THREAD

**Issue by J0F3** [PowerShell/PowerShellGallery#225] opened 2022-04-22 15:09 UTC
[powershellgallery.com](http://powershellgallery.com/) responses very slow and also installing modules takes approximately three times longer or more that normal. 

Experience the same problem from different location / internet connections and it seems getting worse than better.

**Comment by Veradux21** [comment] 2022-04-22 19:12
Same, site seems to be totally unavailable, and then intermittently comes back.
Also getting:
`Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.`

**Comment by kevinholtkamp** [comment] 2022-04-26 19:32
+1
lately it has been very slow and occasionally unavailable

**Comment by robinmalik** [comment] 2022-04-27 13:23
+1. Today it took well over an hour for an attempted install of `VMware.PowerCLI` to terminate and tell me I needed to run it with `-AllowClobber`.  Even just trying to install the `MicrosoftTeams` module took about 5 minutes.

**Comment by SydneyhSmith** [comment] 2022-04-27 14:32
Thanks everyone for the reports! We are investigating this issue... please feel free to continue to provide us with reports (time stamps for lack of availability are also helpful) as convenient to you

**Comment by KirkH420** [comment] 2022-04-27 18:38
Noticeably slow.

**Comment by o-l-a-v** [comment] 2022-04-28 10:58
API for checking available packages and versions are super slow now. From Norway. Each request takes about 10-15 seconds to complete, with following code:

```powershell
#region    Get-PowerShellGalleryPackageLatestVersion
function Get-PowerShellGalleryPackageLatestVersion {
    <#
        .SYNAPSIS
            Fetches latest version number of a given pacakge (module or script) from PowerShellGallery.
            
        .PARAMETER ModuleName
            String, name of the package (module or script) you want to check.
    #>            
    [CmdletBinding(SupportsPaging=$false)]
    [OutputType([System.Version])]    
    param(
        [Parameter(Mandatory, HelpMessage = 'Name of the PowerShellGallery package (module or script) to fetch.')]
        [ValidateNotNullOrEmpty()]
        [Alias('ModuleName','ScriptName')]
        [string] $PackageName
    )

    Begin {
        if (-not$(Try{$null = Get-Variable -Name 'Random' -Scope 'Script' 2>$null; $?}Catch{$false})) {
            $null = Set-Variable -Name 'Random' -Scope 'Script' -Option 'ReadOnly' -Force -Value (
                [random]::new()
            )
        }
    }

    Process {
        # Access the main module page, and add a random number to trick proxies
        $Url = [string]('https://www.powershellgallery.com/packages/{0}/?dummy={1}' -f ($PackageName,$Script:Random.Next(9999)))
        Write-Debug -Message ('URL for module "{0}" = "{1}".' -f ($PackageName,$Url))
            

        # Create Request Url
        $Request = [System.Net.WebRequest]::Create($Url)
            

        # Do not allow to redirect. The result is a "MovedPermanently"
        $Request.'AllowAutoRedirect' = $false
        $Request.'Proxy' = $null

            
        # Try to get published version number
        Try {
            # Send the request
            $Response = $Request.GetResponse()
               
            # Get back the URL of the true destination page, and split off the version
            $Version = [System.Version]$($Response.GetResponseHeader('Location').Split('/')[-1])
        }
        Catch {
            # Write warning if it failed & return blank version number.
            Write-Warning -Message ($_.'Exception'.'Message')
            $Version = [System.Version]('0.0.0.0')
        }
        Finally {
            # Make sure to clean up connection
            $Response.Close()
            $Response.Dispose()
        }


        # Return Version
        return $Version
    }

    End {}
}
#endregion Get-PowerShellGalleryPackageLatestVersion
```

Usually it takes less than a second.

**Comment by potatoqualitee** [comment] 2022-04-28 13:41
The gallery is unusable today. It's taking 3 minutes to find a module.

![image](https://user-images.githubusercontent.com/8278033/165764614-3cb80362-7ee6-4ff7-9a0b-4dd547392099.png)

And it's impossible to publish a new version of dbatools even with `$PSDefaultParameterValues["*:Timeout"] = 1200 # 20 minutes`

```
Publish-Module encountered an error: Failed to publish module 'dbatools': 'nuget.exe failed to push A task was canceled.
  Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.
```

**Comment by jwyza-pi** [comment] 2022-04-28 14:54
I just tried to install the AZ modules, and after almost an hour of waiting for it to find all the packages, it then failed with an error asking to allow clobber.  :(

**Comment by jeremyguthrie** [comment] 2022-04-29 19:12
Just reporting it is still pretty bad today.  13 minutes to install az one time, currently at 40 minutes and not done searching to even install yet.

**Comment by SydneyhSmith** [comment] 2022-05-02 15:24
Wanted to just add that we are actively investigating the root cause and have been making adjustments to improve the availability over the last few days and hope to have more updates soon.... appreciate the patience with the unsatisfying update

**Comment by SydneyhSmith** [comment] 2022-05-03 16:38
We deployed an update last night which we believe should have resulted in a significant performance improvement based on our monitoring....are folks seeing any improvement today?

**Comment by o-l-a-v** [comment] 2022-05-03 17:01
Seems the PowerShellGallery API responds much faster now at least. :) Even better than before this incident.

**Comment by robinmalik** [comment] 2022-05-05 11:24
Thanks for the update @SydneyhSmith. Looking better than 5 minutes now:

```
Measure-Command { Install-Module -Name MicrosoftTeams -Scope AllUsers -Force }
TotalSeconds      : 24.8101738
```

**Comment by SydneyhSmith** [comment] 2022-05-05 19:31
Thanks everyone, going to close this as mitigated for now, please re-open if you are still hitting this issue (we are continuing to invest in performance improvements on the Gallery and Get sides)

**Closed by SydneyhSmith** 2022-05-05 19:31 UTC
