### ISSUE TITLE
https://www.powershellgaller.com unavailable / error 500

### ISSUE THREAD

**Issue by devaccount89** [PowerShell/PowerShellGallery#137] opened 2020-10-30 12:22 UTC
When try to accessing https://www.powershellgaller.com  I do not get a response / takes very long / or returns error 500.

**Comment by sigv** [comment] 2020-10-30 12:34
This appears to be a duplicate of #135 which has more details on the status.

Furthermore [psgallery_status.md](https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md) can be seen to list _the PowerShell Gallery is currently: Experiencing an outage_.

**Comment by devaccount89** [comment] 2020-10-30 12:41
> This appears to be a duplicate of #135 which has more details on the status.
> 
> Furthermore [psgallery_status.md](https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md) can be seen to list _the PowerShell Gallery is currently: Experiencing an outage_.

ah Yes- thank you. This was a new update- I was looking at the dates below the status and there was no info given. Since the other issue #135 was opened 6 hours ago and we did not have a new timestamp on the psgallery- I thought that this must be unrelated.

**Comment by SydneyhSmith** [comment] 2020-10-30 15:31
Thanks--we are still working hard on the outage, I will close this as a duplicate

**Closed by SydneyhSmith** 2020-10-30 15:31 UTC
