### ISSUE TITLE
Filter Option Doesn't work for module and script filter

### ISSUE THREAD

**Issue by ankitkotnala** [PowerShell/PowerShellGallery#64] opened 2019-07-26 19:36 UTC
While searching for Scripts/ Modules in PS Gallery , if you put a filter for any one of them and navigate to next page the filter resets and we see results for both filters.
Same thing happens on searching for specific filter

**Comment by SydneyhSmith** [comment] 2019-07-30 15:45
Thanks for reporting this issue @ankitkotnala I can easily reproduce this bug...I am going to close this issue as a duplicate of #49 where we are already tracking this bug. Thanks!

**Closed by SydneyhSmith** 2019-07-30 15:45 UTC
