### ISSUE TITLE
PowerShell Gallery down?

### ISSUE THREAD

**Issue by Jezzy29** [PowerShell/PowerShellGallery#139] opened 2020-10-30 13:57 UTC
My Azure devops pipelines are failing :
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.

Is that known as today?

Regards

**Comment by venkat1017** [comment] 2020-10-30 14:15
This appears to be a duplicate of #135 which has more details on the status.

Furthermore psgallery_status.md can be seen to list the PowerShell Gallery is currently: Experiencing an outage.

**Comment by jessehouwing** [comment] 2020-10-30 14:16
It's not like the other 3 issues aren't recent and have a pretty descriptive title already... ;o)

![image](https://user-images.githubusercontent.com/4173387/97715565-db4a7680-1ac2-11eb-872a-0c6d2a6eeb30.png)

**Closed** 2020-10-30 14:16 UTC
