### ISSUE TITLE
Unable to resolve package source 'https://www.powershellgallery.com/api/v2'

### ISSUE THREAD

**Issue by nodenks** [PowerShell/PowerShellGallery#142] opened 2020-11-05 09:45 UTC
Hi Team,

Since yesterday evening I am getting problems with getting packages from Powershell gallery:
Strange thing is that when I am using PowerShell 7 I got this error but with PS5 it works fine.

PS C:\Program Files\PowerShell\7-preview> [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
PS C:\Program Files\PowerShell\7-preview> Install-Module -Name DataGateway
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
Install-Package: C:\program files\powershell\7-preview\Modules\PowerShellGet\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No match was found for the specified search criteria and module name 'DataGateway'. Try
     | Get-PSRepository to see all available registered module repositories.

**Comment by SydneyhSmith** [comment] 2020-11-19 20:31
Thanks @nodenks are you still seeing this issue?

**Comment by Saved-by-Him** [comment] 2021-02-09 04:03
Having similar issue here : WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/'.

Windows 8.1 x64

PSVersion 5.1.14409.1018
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14409.1018
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Comment by SydneyhSmith** [comment] 2021-02-10 19:20
Closing this as a duplicate of https://github.com/PowerShell/PowerShellGallery/issues/153

**Closed** 2021-02-10 19:20 UTC
